/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as PhoneOtpRouteImport } from './routes/phone-otp'
import { Route as RegRouteImport } from './routes/reg'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneOtpRoute = PhoneOtpRouteImport.update({
  id: '/phone-otp',
  path: '/phone-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegRoute = RegRouteImport.update({
  id: '/reg',
  path: '/reg',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/compare': typeof CompareRoute
  '/confirm': typeof ConfirmRoute
  '/otp': typeof OtpRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/phone': typeof PhoneRoute
  '/phone-otp': typeof PhoneOtpRoute
  '/reg': typeof RegRoute
  '/success': typeof SuccessRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/compare': typeof CompareRoute
  '/confirm': typeof ConfirmRoute
  '/otp': typeof OtpRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/phone': typeof PhoneRoute
  '/phone-otp': typeof PhoneOtpRoute
  '/reg': typeof RegRoute
  '/success': typeof SuccessRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/compare': typeof CompareRoute
  '/confirm': typeof ConfirmRoute
  '/otp': typeof OtpRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/phone': typeof PhoneRoute
  '/phone-otp': typeof PhoneOtpRoute
  '/reg': typeof RegRoute
  '/success': typeof SuccessRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/compare'
    | '/confirm'
    | '/otp'
    | '/owner'
    | '/payment'
    | '/phone'
    | '/phone-otp'
    | '/reg'
    | '/success'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/compare'
    | '/confirm'
    | '/otp'
    | '/owner'
    | '/payment'
    | '/phone'
    | '/phone-otp'
    | '/reg'
    | '/success'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/compare'
    | '/confirm'
    | '/otp'
    | '/owner'
    | '/payment'
    | '/phone'
    | '/phone-otp'
    | '/reg'
    | '/success'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  CompareRoute: typeof CompareRoute
  ConfirmRoute: typeof ConfirmRoute
  OtpRoute: typeof OtpRoute
  OwnerRoute: typeof OwnerRoute
  PaymentRoute: typeof PaymentRoute
  PhoneRoute: typeof PhoneRoute
  PhoneOtpRoute: typeof PhoneOtpRoute
  RegRoute: typeof RegRoute
  SuccessRoute: typeof SuccessRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-otp': {
      id: '/phone-otp'
      path: '/phone-otp'
      fullPath: '/phone-otp'
      preLoaderRoute: typeof PhoneOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reg': {
      id: '/reg'
      path: '/reg'
      fullPath: '/reg'
      preLoaderRoute: typeof RegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  CompareRoute: CompareRoute,
  ConfirmRoute: ConfirmRoute,
  OtpRoute: OtpRoute,
  OwnerRoute: OwnerRoute,
  PaymentRoute: PaymentRoute,
  PhoneRoute: PhoneRoute,
  PhoneOtpRoute: PhoneOtpRoute,
  RegRoute: RegRoute,
  SuccessRoute: SuccessRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
